CREATE TABLE LONG_TERM_LFG_MESSAGE
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    LFG_ID        INTEGER NOT NULL,
    GUILD_ID      TEXT    NOT NULL,
    CHANNEL_ID    TEXT    NOT NULL,
    THREAD_ID     TEXT,
    MESSAGE_ID    TEXT    NOT NULL,
    TYPE          TEXT    NOT NULL CHECK ( TYPE = 'NORMAL' OR TYPE = 'THREAD_ROOT' ),
    RAW_TIMESTAMP INTEGER NOT NULL,
    FOREIGN KEY (LFG_ID) REFERENCES LONG_TERM_LFG (ID) ON DELETE CASCADE
);
