CREATE TABLE NORMAL_LFG_THREAD
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    LFG_ID     INTEGER UNIQUE NOT NULL,
    GUILD_ID   TEXT           NOT NULL,
    CHANNEL_ID TEXT           NOT NULL,
    THREAD_ID  TEXT           NOT NULL,
    FOREIGN KEY (LFG_ID) REFERENCES NORMAL_LFG (ID) ON DELETE CASCADE
);
