CREATE TABLE SERVER_LFG_CONFIG
(
    ID                           INTEGER PRIMARY KEY AUTOINCREMENT,
    GUILD_ID                     TEXT NOT NULL UNIQUE,
    NORMAL_LFG_THREAD_CHANNEL    TEXT,
    LONG_TERM_LFG_THREAD_CHANNEL TEXT,
    REGULAR_LFG_THREAD_CHANNEL   TEXT,
    NORMAL_LFG_LIST_CHANNEL      TEXT,
    LONG_TERM_LFG_LIST_CHANNEL   TEXT,
    REGULAR_LFG_LIST_CHANNEL     TEXT,
    EXPIRED_LFG_DELETE_DELAY     INTEGER
);
